# Generated by Django 4.0.3 on 2022-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_profile_avatar_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='resturant',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='logos'),
        ),
    ]
